# Benchmark SOCP Solvers with Limited Solve Time
Based on MCU benchmarks, we obtain time/iter for each solver. Then we can compute the maximum number of iterations for each solver given a fixed control frequency. We evaluate solution and performace of each solver with respect to this.

In [1]:
using Pkg
Pkg.activate(@__DIR__)
Pkg.instantiate()

using LinearAlgebra
using Printf
using ForwardDiff
using JuMP
using ECOS
using SCS
using Random
using PyPlot

  Activating environment at `~/tinympc-dev-julia/rocket_landing_Zac/Project.toml`


In [2]:
include("JuMP_MPC.jl")
include("../LibTinyMPC_clean.jl")

reset_solver! (generic function with 1 method)

## Rocket Soft Landing

In [55]:
#Rocket landing
NSTATES = 6
NINPUTS = 3
NHORIZON = 21
NTOTAL = 301

# Initialize cache, settings, bounds, socs, workspace, solver

###### Cache
rho = 1e0
Kinf = zeros(NINPUTS,NSTATES)
Pinf = zeros(NSTATES,NSTATES)
Quu_inv = zeros(NINPUTS,NINPUTS)
AmBKt = zeros(NSTATES,NSTATES)
APf = zeros(NSTATES)
BPf = zeros(NINPUTS)
my_cache = TinyCache(rho, Kinf, Pinf, Quu_inv, AmBKt, APf, BPf)
#####

##### Settings
abs_pri_tol = 1e-2
abs_dua_tol = 1e-2
max_iter = 100
check_termination = 1
en_state_bound = 0  # ENABLE CONSTRAINTS OR NOT
en_input_bound = 1
en_state_soc = 0
en_input_soc = 1
my_stgs = TinySettings(abs_pri_tol, abs_dua_tol, max_iter, check_termination, en_state_bound, en_input_bound, en_state_soc, en_input_soc)
#####

###### Bounds
umin = -10.0*ones(NINPUTS, NHORIZON-1)
umax = 105*ones(NINPUTS, NHORIZON-1)
xmin = repeat([-4.5; -4.5; -0.5; -10; -10; -20], 1, NHORIZON)
xmax = repeat([4.5; 4.5; 100.0; 10; 10; 20], 1, NHORIZON)
z = zeros(NINPUTS, NHORIZON-1)
znew = zeros(NINPUTS, NHORIZON-1)
v = zeros(NSTATES, NHORIZON)
vnew = zeros(NSTATES, NHORIZON)
y = zeros(NINPUTS, NHORIZON-1)
g = zeros(NSTATES, NHORIZON)
my_bounds = TinyBounds(umin, umax, xmin, xmax, z, znew, v, vnew, y, g)
#####

##### SOCS
ncu = 1
ncx = 1
cu = [0.25, 0]  # 0.3 is the thrust coefficient
cx = [0.5, 0]
qcu = [3, 0]  # 3 is the dimensions of 1st cone
qux = [3, 0]
Acu = [1, 0]
Acx = [1, 0]
zc = [zeros(NINPUTS, NHORIZON-1), zeros(NINPUTS, NHORIZON-1)]
vc = [zeros(NSTATES, NHORIZON), zeros(NSTATES, NHORIZON)]
zcnew = [zeros(NINPUTS, NHORIZON-1), zeros(NINPUTS, NHORIZON-1)]
vcnew = [zeros(NSTATES, NHORIZON), zeros(NSTATES, NHORIZON)]
yc = [zeros(NINPUTS, NHORIZON-1), zeros(NINPUTS, NHORIZON-1)]
gc = [zeros(NSTATES, NHORIZON), zeros(NSTATES, NHORIZON)]
my_socs = TinySocs(ncu, ncx, cu, cx, qcu, qux, Acu, Acx, zc, zcnew, vc, vcnew, yc, gc)
#####

##### Workspace
x = zeros(NSTATES, NHORIZON)
u = zeros(NINPUTS, NHORIZON-1)
q = zeros(NSTATES, NHORIZON)
r = zeros(NINPUTS, NHORIZON-1)
p = zeros(NSTATES, NHORIZON)
d = zeros(NINPUTS, NHORIZON-1)
pri_res_state = 1.0
pri_res_input = 1.0
dua_res_state = 1.0
dua_res_input = 1.0
status = 0
iter = 0
Q = 1e3*I(NSTATES)
R = 1e0*I(NINPUTS)
Adyn = [1.0 0.0 0.0 0.05 0.0 0.0; 
    0.0 1.0 0.0 0.0 0.05 0.0; 
    0.0 0.0 1.0 0.0 0.0 0.05; 
    0.0 0.0 0.0 1.0 0.0 0.0; 
    0.0 0.0 0.0 0.0 1.0 0.0; 
    0.0 0.0 0.0 0.0 0.0 1.0]
Bdyn = [0.000125 0.0 0.0; 
    0.0 0.000125 0.0;
    0.0 0.0 0.000125; 
    0.005 0.0 0.0; 
    0.0 0.005 0.0; 
    0.0 0.0 0.005]
fdyn = [0.0, 0.0, -0.0122625, 0.0, 0.0, -0.4905] * 1

h = 0.05
t = h*(0:NTOTAL-1)
Xref = zeros(NSTATES, NTOTAL)
x0 = [4, 2, 20, -3, 2, -4.5]  # INITIAL STATE
# x0 = [4, 2, 20, -2, 1, -4.0]
x[:,1] = 1*x0
xg = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
for k = 1:NTOTAL
  Xref[:,k] = x0 + (xg - x0)*(k-1)/(NTOTAL-1)
end
# append zeros to Xref
Xref = hcat([Xref zeros(NSTATES, NHORIZON)])
Uref = repeat([0; 0; 10.0], 1, NTOTAL-1) 
Xref_hrz = 1*Xref[:,1:NHORIZON]
Uref_hrz = 1*Uref[:,1:NHORIZON-1]
# Could provide a better reference from other solvers

Qu = zeros(NINPUTS, NINPUTS)
my_work = TinyWorkspace(x, u, q, r, p, d, pri_res_state, pri_res_input, dua_res_state, dua_res_input, status, iter, Q, R, Adyn, Bdyn, fdyn, Xref_hrz, Uref_hrz, Qu, my_bounds, my_socs)
#####

# Solver
solver = TinySolver(my_stgs, my_cache, my_work)

TinySolver(TinySettings(0.01, 0.01, 100, 1, 0, 1, 0, 1), TinyCache(1.0, [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0]), TinyWorkspace([4.0 0.0 … 0.0 0.0; 2.0 0.0 … 0.0 0.0; … ; 2.0 0.0 … 0.0 0.0; -4.5 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], 1.0, 1.0, 1.0, 1.0, 0, 0, [1000.0 0.0 … 0.0 0.0; 0.0 1000.0 … 0.0 0.0; … ; 0.0 0.0 … 1000.0 0.0; 0.0 0.0 … 0.0 1000.0], [1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0], [1.0 0.0 … 0.0 

In [56]:
params = (
    Nh = NHORIZON,
    nx = NSTATES,
    nu = NINPUTS,
    ncx = en_state_bound,
    ncu = en_input_bound,
    ncg = 0,
    ncu_cone = en_input_soc,
    ncx_cone = en_state_soc,
    c_cone = cu,
    Q = Q*1+rho*I*0,
    R = R*1+rho*I*0,
    Qf = Q*1+rho*I*0,
    u_min = umin[:,1],
    u_max = umax[:,1],
    x_min = xmin[:,1],
    x_max = xmax[:,1],
    Xref = Xref_hrz,
    Uref = Uref_hrz,
    Adyn = Adyn,
    Bdyn = Bdyn,
    fdyn = fdyn,
);

Xhrz = zeros(NSTATES, NHORIZON)
Xhrz[:,1] = x0*1
Uhrz = zeros(NINPUTS, NHORIZON-1)

tpis = [200.0, 200.0, 90.0] # time (us) per iteration for solvers (taken for MCU)

3-element Vector{Float64}:
 200.0
 200.0
  90.0

## MPC

In [138]:
clamp.([-100, 120, 110], params.u_min, params.u_max)

3-element Vector{Float64}:
 -10.0
 105.0
 105.0

### Get data for one solver at one frequency

In [134]:
# MPC loop for each
# opti = "ECOS"
# opti = "SCS"
opti = "TinyMPC"

freq = 200.0  # Hz
optimizers = (
    # Use ECOS [1]
    JuMP.optimizer_with_attributes(ECOS.Optimizer, 
        "verbose"=>false, "abstol"=>1e-2, "reltol"=>1e-2, "maxit"=>round(Int, 1e6/freq/tpis[1])),
    # Use SCS [2]
    JuMP.optimizer_with_attributes(SCS.Optimizer, 
    "verbose"=>false, "eps_abs"=>1e-2, "eps_rel"=>1e-2, "max_iters"=>round(Int, 1e6/freq/tpis[2])),
    "TinyMPC")
solver.settings.max_iter = round(Int, 1e6/freq/tpis[3])

if (opti == "TinyMPC")
    compute_cache!(solver, Q, R)
end

info = SolnStats(0, 0, 0, 0, 0, 0, 0)

Random.seed!(1)
Xhist = zeros(NSTATES, NTOTAL)
Xhist[:,1] .= x0*1.1
Uhist = zeros(NINPUTS, NTOTAL-1)

Xhrz = 1*Xref[:,1:NHORIZON]
Xhrz[:,1] .= Xhist[:,1]
Uhrz = 1*Uref[:,1:NHORIZON-1]

for i = 1:NTOTAL-1
    # i%10 == 0 && print("i = ", i, "\n")
    # Get measurements
    solver.workspace.x[:,1] = Xhist[:,i] 
    Xhrz[:,1] .= Xhist[:,i]
    # print("x = ", solver.workspace.x[:,1], "\n")
    # display(solver.workspace.x[:,1])

    # Update references
    solver.workspace.Xref .= Xref[:,i:i+NHORIZON-1]
    params.Xref .= Xref[:,i:i+NHORIZON-1]
    # solver.workspace.Uref .= Uref[:,i:i+NHORIZON-2]
    # print("xref = ", solver.workspace.Xref[:,1], "\n")
    # display(solver.workspace.Xref[:,1])
    
    # Solve
    if (opti == "ECOS")
        solve_mpc_JuMP(optimizers[1], params, Xhrz, Uhrz; warm_start=false)
    elseif (opti == "SCS")
        solve_mpc_JuMP(optimizers[2], params, Xhrz, Uhrz; warm_start=false)        
    else
        solve_admm!(solver)
        Xhrz .= solver.workspace.x
        Uhrz .= solver.workspace.u
    end
    check_solution!(info, opti, params, Xhrz, Uhrz)    
    Uhist[:,i] .= Uhrz[:,1]
    
    # print("u = ", Uhist[:,i], "\n")
    # display(Uhist[:,i])

    # Simulate
    Uhist[:,i] = clamp.(Uhist[:,i], params.u_min, params.u_max)

    Xhist[:,i+1] .= Adyn*Xhist[:,i] + Bdyn*Uhist[:,i] + fdyn
    # display(Xhrz)
    # display(Uhrz)
end
info.tracking_error = norm(Xhist[:,NTOTAL] - xg)

3-element Vector{Float64}:
  24.81537765554906
 -10.680719460736611
 107.36255534466659

3-element Vector{Float64}:
  24.327180611820495
 -10.070464400802862
 105.23649317983273

3-element Vector{Float64}:
  24.187114788927136
 -10.042887461010622
 104.93226300549912

3-element Vector{Float64}:
  24.331349184201713
 -10.020045097894922
 105.13330723844365

3-element Vector{Float64}:
  24.327262678171465
 -10.01972520892123
 105.09757332135143

3-element Vector{Float64}:
  24.316035869661842
 -10.025878784340549
 105.06528814314726

3-element Vector{Float64}:
  24.35098103145171
 -10.004489200801842
 105.17010141871015

3-element Vector{Float64}:
  24.332227183015714
 -10.01949869561497
 105.07478782403211

3-element Vector{Float64}:
  24.361653744812987
  -9.995864183716819
 105.18441685707597

3-element Vector{Float64}:
  24.356862270599223
 -10.004246141938182
 105.12841598272121

3-element Vector{Float64}:
  24.370737274726178
  -9.999349740060254
 105.13346519470707

3-element Vector{Float64}:
  24.34105611849254
  -9.98329233157692
 105.1787090411724

3-element Vector{Float64}:
  24.247075439763364
 -10.01108425371909
 104.96707116060844

3-element Vector{Float64}:
  24.24621415032161
  -9.974360527844965
 105.1327991666567

3-element Vector{Float64}:
  24.264652758825008
  -9.992656404987471
 105.04116492621193

3-element Vector{Float64}:
  24.20247350882763
  -9.97713680262909
 105.07428068458526

3-element Vector{Float64}:
  24.14877464107736
  -9.984431774654894
 104.99172017851552

3-element Vector{Float64}:
  24.237227232683416
  -9.996554397900155
 104.98481398523464

3-element Vector{Float64}:
  24.094463167112586
  -9.997492625149647
 104.91002963690272

3-element Vector{Float64}:
  24.107281641563944
 -10.008705300583301
 104.8528171736447

3-element Vector{Float64}:
  24.2388340715203
  -9.990449500996846
 105.02088428424523

3-element Vector{Float64}:
  24.138592715178756
 -10.004874085507623
 104.89044300405158

3-element Vector{Float64}:
  24.458497005465528
  -9.97371376613458
 105.19147484834068

3-element Vector{Float64}:
  24.338427360324054
  -9.970246803698913
 105.13007896463725

3-element Vector{Float64}:
  24.328314758109784
  -9.970867213672278
 105.09086441588727

3-element Vector{Float64}:
  24.360789501854896
  -9.968904338107421
 105.12847730392997

3-element Vector{Float64}:
  24.328917810259377
  -9.972080329885259
 105.09006181680274

3-element Vector{Float64}:
   0.43477216227517346
  -9.974125236425493
 105.0492158354541

3-element Vector{Float64}:
  -0.5055388019738274
  -9.972385562116386
 105.0495201466403

3-element Vector{Float64}:
  -0.38402204077740976
  -9.970773209976514
 105.04847875640405

3-element Vector{Float64}:
  -0.3670073675865453
  -9.969168005611593
 105.04736457209927

3-element Vector{Float64}:
  -0.3574098010031008
  -9.967563433088472
 105.04624661113883

3-element Vector{Float64}:
  -0.3475338815967035
  -9.965959139073732
 105.04512861562219

3-element Vector{Float64}:
  -0.33788565164029194
  -9.964355104370242
 105.0440107884182

3-element Vector{Float64}:
  -0.3285080360621109
 -10.024441268417647
 105.04289314049964

3-element Vector{Float64}:
  -0.319390979993301
 -10.019494573738896
 105.04177567243394

3-element Vector{Float64}:
  -0.31052693491967887
 -10.020941879334856
 105.04065838422363

3-element Vector{Float64}:
  -0.3037235750322438
  -9.968897414754906
 105.04136053931973

3-element Vector{Float64}:
  -0.29058358381008276
 -10.028763490572246
 105.03852853450863

3-element Vector{Float64}:
  -0.2863469466715287
 -10.017443049108635
 105.03547132364201

3-element Vector{Float64}:
  -0.2736212228421948
 -10.018595688907553
 105.03554050507643

3-element Vector{Float64}:
  -0.26629123884860206
 -10.028992020173362
 105.04476895954514

3-element Vector{Float64}:
  -0.2718361825598379
 -10.00757004884332
 105.02826118866287

3-element Vector{Float64}:
  -0.25483454311358145
 -10.01062617801037
 105.02670357171914

3-element Vector{Float64}:
  -0.23435449253818774
 -10.033396191332457
 105.047335798651

3-element Vector{Float64}:
  -0.2597113893301142
  -9.994439699827538
 105.01837160952368

3-element Vector{Float64}:
  -0.2331372500059672
  -9.999361632070858
 105.01709373651835

3-element Vector{Float64}:
  -0.20748894344282576
 -10.042226136562476
 105.0345629184265

3-element Vector{Float64}:
  -0.2507949099199891
  -9.979629395330946
 105.0047636453497

3-element Vector{Float64}:
  -0.19799422542542544
 -10.005213991408382
 105.02929041040113

3-element Vector{Float64}:
  -0.23297423414800988
  -9.971002458625875
 104.99183717226677

3-element Vector{Float64}:
  -0.2127393502587296
  -9.953981998037051
 104.98379180240926

3-element Vector{Float64}:
  -0.16441145619106123
  -9.999654087057152
 105.00887799104865

3-element Vector{Float64}:
  -0.24068432935951023
  -9.935949379379664
 104.96667867117222

3-element Vector{Float64}:
  -0.1546229646152355
  -9.985132792081302
 105.01745603150815

3-element Vector{Float64}:
  -0.2197195850790976
  -9.932449998600404
 104.95747899112143

3-element Vector{Float64}:
  -0.11905643574706914
  -9.991253253233992
 104.99649373375763

3-element Vector{Float64}:
  -0.22252719968319212
  -9.940248906987257
 104.9511069348219

3-element Vector{Float64}:
  -0.10299861134511445
 -10.006824692199963
 105.01039113394947

3-element Vector{Float64}:
  -0.2310659877654473
  -9.94811405499594
 104.95522625380264

3-element Vector{Float64}:
  -0.06606808580193047
 -10.04865287048542
 105.05342766803741

3-element Vector{Float64}:
  -0.2168345578623132
  -9.976447552786013
 104.97778088919733

3-element Vector{Float64}:
  -0.08817371471175761
 -10.026974821925108
 105.04079302692101

3-element Vector{Float64}:
  -0.1576807712321937
 -10.000408752091445
 104.99990259499448

3-element Vector{Float64}:
  -0.15208275046117592
  -9.999886641578094
 104.99894488722244

3-element Vector{Float64}:
  -0.15214056614206584
 -10.001006400919593
 105.00314587162956

3-element Vector{Float64}:
  -0.13965473537381712
  -9.999004024032509
 105.00687098924892

3-element Vector{Float64}:
  -0.1318016360701364
 -10.004508512205206
 105.00467606652033

3-element Vector{Float64}:
  -0.12212471033248562
 -10.000879703777635
 105.00549986307752

3-element Vector{Float64}:
  -0.12383376419595749
 -10.000437428883792
 105.003842455489

3-element Vector{Float64}:
  -0.11971627893718306
  -9.999500751141877
 105.00294691265255

3-element Vector{Float64}:
  -0.11500323150664116
  -9.998884347106195
 105.0020582873573

3-element Vector{Float64}:
  -0.11604951970593902
 -10.003131699126364
 105.00155289848107

3-element Vector{Float64}:
  -0.3061341151327426
  -1.7541204757987963
 104.99915600318235

3-element Vector{Float64}:
  -0.6600183965520756
   6.905234041153037
 104.99815025806366

3-element Vector{Float64}:
  -1.2125303717075653
  11.4457426617661
 104.99708838068453

3-element Vector{Float64}:
  -1.5252104513003388
  12.607806224207991
 104.99602729684602

3-element Vector{Float64}:
  -1.6172082974158783
  12.083744574119159
 104.99490498482368

3-element Vector{Float64}:
  -1.4743797482552239
  11.084767525336819
 104.99380679704176

3-element Vector{Float64}:
  -1.2556194929335618
  10.162227980707183
 104.99276199036665

3-element Vector{Float64}:
  -1.0894038271922213
   9.45637445236827
 104.99166532362575

3-element Vector{Float64}:
  -0.9414954890531746
   8.922028286357055
 104.9905603634097

3-element Vector{Float64}:
  -0.8228317944302432
   8.482493128223513
 104.98945059065632

3-element Vector{Float64}:
  -0.7674150768763894
   8.084301418163339
 104.9883253293157

3-element Vector{Float64}:
  -0.7138569793767289
   7.703098807854268
 104.98719534406578

3-element Vector{Float64}:
  -0.6747388054623542
   7.3327811883265355
 104.98613695345033

3-element Vector{Float64}:
  -0.6378469530290047
   6.976141729272058
 104.98431999885054

3-element Vector{Float64}:
  -0.6179603428118554
   6.6275149137718685
 104.98390246737783

3-element Vector{Float64}:
  -0.5889164348674782
   6.2965948064404955
 104.9828047956356

3-element Vector{Float64}:
  -0.5627570678696188
   5.983885547902183
 104.9817020137032

3-element Vector{Float64}:
  -0.53917672609996
   5.688246570958448
 104.98059812024903

3-element Vector{Float64}:
  -0.5070825900164664
   5.407973885316181
 104.97949247776263

3-element Vector{Float64}:
  -0.48134366609632906
   5.141708758283137
 104.97838718924328

3-element Vector{Float64}:
  -0.45488230407555363
   4.888511491557395
 104.97728181070266

3-element Vector{Float64}:
  -0.4316144060220779
   4.647692519188219
 104.9761764415713

3-element Vector{Float64}:
  -0.4100284733630488
   4.418670115327423
 104.97507107795303

3-element Vector{Float64}:
  -0.38868841994266035
   4.200894623955257
 104.97396890483381

3-element Vector{Float64}:
  -0.3607020020264855
   3.9938495763250685
 104.97286091076896

3-element Vector{Float64}:
  -0.33939726275477256
   3.79699759414148
 104.97175595462171

3-element Vector{Float64}:
  -0.32160714802355983
   3.609845899955978
 104.97065026075015

3-element Vector{Float64}:
  -0.3055325404161948
   3.4319110625709683
 104.96954011046395

3-element Vector{Float64}:
  -0.2900319299944769
   3.262746639475985
 104.96842925993687

3-element Vector{Float64}:
  -0.27551154469187367
   3.101885902986382
 104.96734357837781

3-element Vector{Float64}:
  -0.25708320435398946
   2.949134559119379
 104.96632034304702

3-element Vector{Float64}:
  -0.2411063466106782
   2.8025123675346677
 104.96515716411818

3-element Vector{Float64}:
  -0.22775873084836462
   2.662532334531086
 104.96406300968813

3-element Vector{Float64}:
  -0.21622684804285797
   2.5302367929288394
 104.9629610839143

3-element Vector{Float64}:
  -0.20531859047555656
   2.4051633640098267
 104.96185822915058

3-element Vector{Float64}:
  -0.19485202332094786
   2.2866249785216155
 104.96075512898095

3-element Vector{Float64}:
  -0.18513594591663463
   2.1740463017418925
 104.95965273101342

3-element Vector{Float64}:
  -0.17518457519394914
   2.0670212744403216
 104.95854952341804

3-element Vector{Float64}:
  -0.16255641790252895
   1.9652438394127891
 104.9574467314068

3-element Vector{Float64}:
  -0.15279486261376363
   1.8684613465435582
 104.95634412132506

3-element Vector{Float64}:
  -0.14462830763729428
   1.776437807799656
 104.95524165597809

3-element Vector{Float64}:
  -0.13706592639423576
   1.688946035116082
 104.9541393438895

3-element Vector{Float64}:
  -0.12997163361242414
   1.6057658384090594
 104.95303719094322

3-element Vector{Float64}:
  -0.12336324403624488
   1.5266852655718317
 104.95193511061866

3-element Vector{Float64}:
  -0.1172731107773366
   1.4515014525573768
 104.95083295404271

3-element Vector{Float64}:
  -0.11224705421186698
   1.3800210282895975
 104.94973115657498

3-element Vector{Float64}:
  -0.10324751030268686
   1.3120637074982753
 104.94863035967761

3-element Vector{Float64}:
  -0.09605727617232063
   1.2474522936742005
 104.94752901270334

3-element Vector{Float64}:
  -0.09030863737347872
   1.1860232280532514
 104.94642786814423

3-element Vector{Float64}:
  -0.08530027648775729
   1.1276195513627556
 104.94532689149108

3-element Vector{Float64}:
  -0.08079912849149551
   1.0720921524950455
 104.94422608442582

3-element Vector{Float64}:
  -0.076700093780115
   1.0192993090248734
 104.94312544777317

3-element Vector{Float64}:
  -0.07289702207352278
   0.9691063511141742
 104.94202492043738

3-element Vector{Float64}:
  -0.06932936486042252
   0.9213853196196595
 104.94092407337217

3-element Vector{Float64}:
  -0.06612380001583062
   0.8760133471584979
 104.93982565477246

3-element Vector{Float64}:
  -0.06218114238588868
   0.8328767773920696
 104.93872468779604

3-element Vector{Float64}:
  -0.05640913689574134
   0.7918638476129054
 104.93762489866423

3-element Vector{Float64}:
  -0.05218802163633285
   0.752870884263384
 104.93652530635332

3-element Vector{Float64}:
  -0.04881931465133249
   0.7157980435923577
 104.93542588412728

3-element Vector{Float64}:
  -0.04606338880732608
   0.6805507178793206
 104.93432663394698

3-element Vector{Float64}:
  -0.043718220012522124
   0.6470390308921239
 104.93322755641739

3-element Vector{Float64}:
  -0.041593715545040766
   0.6151775310925345
 104.93212865207914

3-element Vector{Float64}:
  -0.03957681872412522
   0.5848849907918776
 104.93102989771643

3-element Vector{Float64}:
  -0.037633080638002525
   0.5560843351990314
 104.92993098953082

3-element Vector{Float64}:
  -0.03578942525868811
   0.5287012161822737
 104.92883238135362

3-element Vector{Float64}:
  -0.034589518070557546
   0.5026640030700662
 104.92773793786722

3-element Vector{Float64}:
  -0.030702478857943305
   0.47791664115663224
 104.92663673834073

3-element Vector{Float64}:
  -0.027368810987987047
   0.4543823087011276
 104.92553887990904

3-element Vector{Float64}:
  -0.024984990496641046
   0.4320069785933853
 104.92444006576179

3-element Vector{Float64}:
  -0.023275273711263367
   0.41073404525372226
 104.92333990314609

3-element Vector{Float64}:
  -0.022006015535556145
   0.390508623158091
 104.92223872399816

3-element Vector{Float64}:
  -0.020945891410832473
   0.37127937276667566
 104.92113770597405

3-element Vector{Float64}:
  -0.019952287379670253
   0.3530040108146295
 104.92002650696851

3-element Vector{Float64}:
  -0.018988495157053364
   0.33565352788584946
 104.9189453911528

3-element Vector{Float64}:
  -0.01803199196011107
   0.31836233253510215
 104.91785686775626

3-element Vector{Float64}:
  -0.017112980521581278
   0.30197401022824266
 104.9167604704663

3-element Vector{Float64}:
  -0.016260731583095378
   0.28670654438518994
 104.91566348570935

3-element Vector{Float64}:
  -0.016164249712257828
   0.27244075949473867
 104.91456670518295

3-element Vector{Float64}:
  -0.012987406121961698
   0.22708828138095782
 105.05940770440822

3-element Vector{Float64}:
  -0.010861018202668049
   0.19227307212460687
 105.04239434948948

3-element Vector{Float64}:
  -0.009513268047246726
   0.17291113496007426
 105.05741297874576

3-element Vector{Float64}:
  -0.00854392329431164
   0.1738457091975505
 105.00910454930042

3-element Vector{Float64}:
  -0.008163426827810127
   0.19767716398181534
 105.00749974555742

3-element Vector{Float64}:
  -0.007977395948245203
   0.18578827540542875
 105.02862281553361

3-element Vector{Float64}:
  -0.00731843701745305
   0.1726459673691494
 105.00002977699577

3-element Vector{Float64}:
  -0.007052559778120582
   0.1859226453671461
 105.00268611674181

3-element Vector{Float64}:
  -0.006897087727679718
   0.18561162098927042
 105.00975952472048

3-element Vector{Float64}:
  -0.006401348226049208
   0.17931515420020716
 104.99957722738877

3-element Vector{Float64}:
  -0.006302211580361927
   0.17407690394083986
 104.99564184938723

3-element Vector{Float64}:
  -0.005361342212552245
   0.18685016163283663
 105.00132938394029

3-element Vector{Float64}:
  -0.005464799911415241
   0.1864354867218978
 105.00270002352431

3-element Vector{Float64}:
  -0.004947258924811848
   0.17865749522751173
 105.00454513411157

3-element Vector{Float64}:
  -0.002978989324198267
   0.161112768604184
 105.00476080126411

3-element Vector{Float64}:
  -0.0016867515449767723
   0.14386568027293478
 105.00267116140124

3-element Vector{Float64}:
  -0.0010445460806778328
   0.13118216812197758
 105.00124743944183

3-element Vector{Float64}:
  -0.0008288165042529272
   0.12298973968346161
 105.00056750681202

3-element Vector{Float64}:
  -0.0007857704031373203
   0.11703022217803039
 105.00028851434547

3-element Vector{Float64}:
  -0.0007886912008103764
   0.11150406080963293
 105.00026324939142

3-element Vector{Float64}:
  -0.0007367951345287338
   0.10623267700603378
 105.00015721042766

3-element Vector{Float64}:
  -0.0006994202974510699
   0.09812713462182643
 105.00003606239659

3-element Vector{Float64}:
  -0.0006581509948411224
   0.0908133185308877
 104.99989445105965

3-element Vector{Float64}:
  -0.000614587007042644
   0.08489477489982988
 104.99976364231688

3-element Vector{Float64}:
  -0.000572982326346505
   0.08005749459940859
 104.9996486705283

3-element Vector{Float64}:
  -0.000533973947742794
   0.0758271377034454
 101.95090241884068

3-element Vector{Float64}:
 -0.0004963336460512835
  0.0695178881901235
 88.24310210677476

3-element Vector{Float64}:
 -0.000449162781944068
  0.06523031369284027
 78.91728161567084

3-element Vector{Float64}:
 -0.0005597703643509533
  0.06211056827825345
 75.4401700108462

3-element Vector{Float64}:
  0.0009629044260535125
  0.059301662807314415
 75.5875084229273

3-element Vector{Float64}:
  0.002081978827973785
  0.056501076972910624
 77.13112420831385

3-element Vector{Float64}:
  0.0026109582775397655
  0.053424987235626276
 78.81718997686934

3-element Vector{Float64}:
  0.002684352013677227
  0.04947318472144957
 80.21146129595249

3-element Vector{Float64}:
  0.00256660131022457
  0.04610259405713535
 81.28992431388966

3-element Vector{Float64}:
  0.0024133172060487595
  0.04340502722684292
 82.16258955852624

3-element Vector{Float64}:
  0.0022788843511314383
  0.041148964843486624
 82.9309379097918

3-element Vector{Float64}:
  0.0021681708312897285
  0.03912515979423148
 83.65166243271759

3-element Vector{Float64}:
  0.0020720603703061613
  0.03722391417879933
 84.34554109004146

3-element Vector{Float64}:
  0.001982432296372849
  0.03540538237542279
 85.015235767151

3-element Vector{Float64}:
  0.0018953338628477923
  0.03366246054170574
 85.65796191536484

3-element Vector{Float64}:
  0.001809821357946717
  0.03199767037389023
 86.27131306487243

3-element Vector{Float64}:
  0.0017274075782722775
  0.030413095783316635
 86.85468573945138

3-element Vector{Float64}:
  0.0016482354818609934
  0.028907956411778457
 87.40886804167415

3-element Vector{Float64}:
  0.0015754061792367935
  0.02747934521300266
 87.93529382810735

3-element Vector{Float64}:
  0.0015140986122048616
  0.026123234387551264
 88.43552500690497

3-element Vector{Float64}:
  0.0014587768441085558
  0.02483461879553417
 88.9110210641266

3-element Vector{Float64}:
  0.0016528955179389015
  0.023609385644316916
 89.3630933693183

3-element Vector{Float64}:
  0.0028113702194598744
  0.022446314044238136
 89.7929309868309

3-element Vector{Float64}:
  0.0035729130898296546
  0.021340907168394097
 90.20163001868869

3-element Vector{Float64}:
  0.003830747687620928
  0.02028913160890511
 90.58758083817172

3-element Vector{Float64}:
  0.003770680055394493
  0.01929086468562602
 90.9484219946712

3-element Vector{Float64}:
  0.0035909491649395164
  0.018341150674359596
 91.2967830241987

3-element Vector{Float64}:
  0.003395788677224232
  0.017438489302039173
 91.63247153569618

3-element Vector{Float64}:
  0.0032194051410741054
  0.016580190130774497
 91.95254057000504

3-element Vector{Float64}:
  0.0030635880662277515
  0.015762561457570712
 92.2533138427865

3-element Vector{Float64}:
  0.0029223392578323626
  0.01498860368178967
 92.53462831708346

3-element Vector{Float64}:
  0.002788964848612352
  0.014250897716125976
 92.8055529709139

3-element Vector{Float64}:
  0.0026605751412347445
  0.01354960211556211
 93.06702845711472

3-element Vector{Float64}:
  0.0025362909852901794
  0.012882800624108626
 93.31647715535537

3-element Vector{Float64}:
  0.0024158055733227712
  0.012248879633396825
 93.5534780146171

3-element Vector{Float64}:
  0.0023008447502395057
  0.011645595377506979
 93.76736295377012

3-element Vector{Float64}:
  0.002190741518084849
  0.011072780718016872
 93.97732621428996

3-element Vector{Float64}:
  0.0020855351065378613
  0.010528298303864148
 94.18127841778565

3-element Vector{Float64}:
  0.001986524396313527
  0.010010497489870929
 94.37638337451374

3-element Vector{Float64}:
  0.0018955776872751073
  0.009517971821942695
 94.56185607139562

3-element Vector{Float64}:
  0.0018216743955150605
  0.009050671534513555
 94.72596060049828

3-element Vector{Float64}:
  0.001698262019932173
  0.008605368572119687
 94.88893923220557

3-element Vector{Float64}:
  0.0022554532543210826
  0.00818558022699456
 95.04786222547091

3-element Vector{Float64}:
  0.0031705186662502882
  0.0077831096694414015
 95.20041685328572

3-element Vector{Float64}:
  0.003671669775805242
  0.007397973642596867
 95.34231950634599

3-element Vector{Float64}:
  0.003775005347339544
  0.007021601771171504
 95.47179767007799

3-element Vector{Float64}:
  0.0036668199778926436
  0.006664209571090041
 95.59811930829594

3-element Vector{Float64}:
  0.0034813190513336423
  0.006171443296972612
 95.72166959995063

3-element Vector{Float64}:
  0.003297940085639439
  0.005245496446917741
 95.84085108247419

3-element Vector{Float64}:
  0.0031319185768357016
  0.004511136744049793
 95.94724102062351

3-element Vector{Float64}:
  0.0029828564080034425
  0.004058031982882682
 96.04992908075603

3-element Vector{Float64}:
  0.0028451810071796757
  0.0037833483564106984
 96.14880356106629

3-element Vector{Float64}:
  0.002714449469831237
  0.0035885867370097912
 96.24539287162285

3-element Vector{Float64}:
  0.0025884933023601064
  0.0034197483087936575
 96.33866302904906

3-element Vector{Float64}:
  0.002466748045401701
  0.003256297707682876
 96.41498094363575

3-element Vector{Float64}:
  0.002349359521824468
  0.0030948068510276983
 96.49729227869715

3-element Vector{Float64}:
  0.002236605263932212
  0.002937619907761757
 96.57613730611993

3-element Vector{Float64}:
  0.0021286532807662795
  0.0027873518480205917
 96.65248702403484

3-element Vector{Float64}:
  0.0020255233371191395
  0.0026452656604227798
 96.71576282042847

3-element Vector{Float64}:
  0.0019271269068683594
  0.002511424209750146
 96.78111347265232

3-element Vector{Float64}:
  0.0018335372912723358
  0.0023852801571724314
 96.84684258907807

3-element Vector{Float64}:
  0.0017446207475595443
  0.0022661358380382524
 96.90902988949355

3-element Vector{Float64}:
  0.001660252449440236
  0.0021533650618703604
 96.96193088105284

3-element Vector{Float64}:
  0.0015815008794639596
  0.0020464674411293515
 97.00789815270298

3-element Vector{Float64}:
  0.0015104114766897325
  0.0019450474930202688
 97.06581021146388

3-element Vector{Float64}:
  0.0014624213811051945
  0.0018487778074618433
 97.11868453819105

3-element Vector{Float64}:
  0.001346124092819423
  0.0017573708103686414
 97.1619652122006

3-element Vector{Float64}:
  0.0022313442554393603
  0.0016705631229303464
 97.19025499397401

3-element Vector{Float64}:
  0.002943220384731049
  0.0015881087800551086
 97.24238119476178

3-element Vector{Float64}:
  0.003235209308965814
  0.0015097768208720552
 97.28970225298318

3-element Vector{Float64}:
  0.0032366686947593593
  0.0014353503493245157
 97.32084483246506

3-element Vector{Float64}:
  0.0031085668784740506
  0.0013646257756265712
 97.33863910412819

3-element Vector{Float64}:
  0.0029475622397558965
  0.0012974119120618965
 97.38534309209544

3-element Vector{Float64}:
  0.002794055729028244
  0.0012335289738372168
 97.42886176856095

3-element Vector{Float64}:
  0.0026570146365041403
  0.0011728076055543823
 97.44434546266555

3-element Vector{Float64}:
  0.002533239971698187
  0.0011150880063253155
 97.45929416078081

3-element Vector{Float64}:
  0.0024176615581348315
  0.0010602191733246613
 97.50159015649632

3-element Vector{Float64}:
  0.002306972133538032
  0.0010080582529212734
 97.55204388120093

3-element Vector{Float64}:
  0.0021998687088582436
  0.0009584699791700402
 97.5330961312204

3-element Vector{Float64}:
  0.0020962293040533986
  0.0009113261783904036
 97.55151748563294

3-element Vector{Float64}:
  0.0019963405259657563
  0.0008665053273126944
 97.5940702912607

3-element Vector{Float64}:
  0.0019004753823521625
  0.0008238921523009424
 97.64179604488534

3-element Vector{Float64}:
  0.0018087581675625408
  0.0007833772649608051
 97.61494473995833

3-element Vector{Float64}:
  0.0017211751510215478
  0.0007448568275725265
 97.62757393288906

3-element Vector{Float64}:
  0.0016376272403637593
  0.0007082322442020228
 97.71999963465205

3-element Vector{Float64}:
  0.0015579757846435616
  0.0006734098750884598
 97.69715792373802

3-element Vector{Float64}:
  0.0014820694384347632
  0.0006403007708017938
 97.6641335863018

3-element Vector{Float64}:
  0.001409755907445076
  0.0006088204241354589
 97.78073147288407

3-element Vector{Float64}:
  0.0013408855431618072
  0.0005788885379089947
 97.82457379499114

3-element Vector{Float64}:
  0.0012753118620011383
  0.0005504288069957397
 97.76032507249411

3-element Vector{Float64}:
  0.0012128914932217905
  0.000523368713259309
 97.92115349930471

3-element Vector{Float64}:
  0.0011534843423649521
  0.0004976393324813699
 98.09384201582927

3-element Vector{Float64}:
  0.0010969539870399059
  0.00047317515185518744
 98.04465077981256

3-element Vector{Float64}:
  0.0010431681298533751
  0.0004499138977642758
 98.30032915035379

3-element Vector{Float64}:
  0.0009919989724087863
  0.0004277963731924572
 98.86973681585457

3-element Vector{Float64}:
  0.0009433234608189345
  0.0004067663032856217
 98.85505239968346

3-element Vector{Float64}:
  0.0008970234071352667
  0.0003867701894706421
 98.83360119440718

3-element Vector{Float64}:
  0.0008529855159381539
  0.00036775717115933304
 98.8152237504418

3-element Vector{Float64}:
  0.0008111013429813463
  0.0003496788943038176
 98.79602445489711

3-element Vector{Float64}:
  0.0007712672098723061
  0.00033248938707641784
 98.77690210089192

3-element Vector{Float64}:
  0.0007333840885110909
  0.0003161449417450335
 98.75808477164614

3-element Vector{Float64}:
  0.0006973574656417014
  0.0003006040027686563
 98.73967165403549

3-element Vector{Float64}:
  0.0006630971946712805
  0.00028582705998170255
 98.72168693811368

3-element Vector{Float64}:
  0.0006305173384564267
  0.0002717765477542322
 98.70398704168545

3-element Vector{Float64}:
  0.0005995360082069467
  0.0002584167489472211
 98.6870131678451

3-element Vector{Float64}:
   0.7218857652454178
   0.3395289557589183
 103.78090973284336

3-element Vector{Float64}:
   1.1407327599113761
   0.5144547819152925
 103.78570999999103

3-element Vector{Float64}:
   1.2949855898989724
   0.5457685224304031
 103.71037971592173

3-element Vector{Float64}:
   1.3232217398995676
   0.5081463090196181
 103.65207412567325

3-element Vector{Float64}:
   1.3228410896221947
   0.45525688550467125
 103.58785977924649

3-element Vector{Float64}:
   1.3358293295915382
   0.4105533846856897
 103.51715335479372

3-element Vector{Float64}:
   1.3702012364867224
   0.3782297104841005
 103.4402635590327

3-element Vector{Float64}:
   1.4210666076512766
   0.35479979415726937
 103.35736811906055

3-element Vector{Float64}:
   1.482140556468838
   0.3358380681819013
 103.26863338652308

3-element Vector{Float64}:
   1.549537971014984
   0.3184142012435509
 103.17422164631984

3-element Vector{Float64}:
   1.6217814562986015
   0.30121594791519646
 103.074290587429

3-element Vector{Float64}:
   1.6987215271549345
   0.2839555868147924
 102.9689933726028

3-element Vector{Float64}:
   1.7804723478688351
   0.2669012184937579
 102.8583597596986

3-element Vector{Float64}:
   1.8664172250482325
   0.2508681021155076
 102.75231258105045

3-element Vector{Float64}:
   1.953726739251334
   0.23788397616743406
 104.76107484496632

3-element Vector{Float64}:
   2.034180323211119
   0.23302980770223214
 104.9999241196382

3-element Vector{Float64}:
   2.0866827424713787
   0.24882576181914684
 104.99984497184342

3-element Vector{Float64}:
   2.059445117210392
   0.31558859851926624
 105.00005403694972

3-element Vector{Float64}:
   1.827525592484342
   0.5060247615203779
 105.00001988983963

0.8725188815332116

In [133]:
info

SolnStats(0.0, 0.0, 2.3624945503773915, 0.01426348227557467, 0.23624758370933918, 0.001666253324915339, 0.8725188674183626)

### Get data for all solvers at one frequency

In [68]:
infos = [SolnStats(0, 0, 0, 0, 0, 0, 0), SolnStats(0, 0, 0, 0, 0, 0, 0), SolnStats(0, 0, 0, 0, 0, 0, 0)]
if 1==1
    optis = ["ECOS", "SCS", "TinyMPC"]    
    freq = 500.0
    optimizers = (
        # Use ECOS [1]
        JuMP.optimizer_with_attributes(ECOS.Optimizer, 
            "verbose"=>false, "abstol"=>1e-2, "reltol"=>1e-2, "maxit"=>round(Int, 1e6/freq/tpis[1])),
        # Use SCS [2]
        JuMP.optimizer_with_attributes(SCS.Optimizer, 
        "verbose"=>false, "eps_abs"=>1e-2, "eps_rel"=>1e-2, "max_iters"=>round(Int, 1e6/freq/tpis[2])),
        "TinyMPC")
    solver.settings.max_iter = round(Int, 1e6/freq/tpis[3])

    for solver_idx = 1:length(optis)
        opti = optis[solver_idx]
        if (opti == "TinyMPC")
            compute_cache!(solver, Q, R)
        end
        
        Random.seed!(1)
        Xhist = zeros(NSTATES, NTOTAL)
        Xhist[:,1] .= x0*1.1
        Uhist = zeros(NINPUTS, NTOTAL-1)

        Xhrz = 1*Xref[:,1:NHORIZON]
        Xhrz[:,1] .= Xhist[:,1]
        Uhrz = 1*Uref[:,1:NHORIZON-1]

        for i = 1:NTOTAL-1
            # i%10 == 0 && print("i = ", i, "\n")
            # Get measurements
            solver.workspace.x[:,1] = Xhist[:,i] 
            Xhrz[:,1] .= Xhist[:,i]
            # print("x = ", solver.workspace.x[:,1], "\n")
            # display(solver.workspace.x[:,1])

            # Update references
            solver.workspace.Xref .= Xref[:,i:i+NHORIZON-1]
            params.Xref .= Xref[:,i:i+NHORIZON-1]
            # solver.workspace.Uref .= Uref[:,i:i+NHORIZON-2]
            # print("xref = ", solver.workspace.Xref[:,1], "\n")
            # display(solver.workspace.Xref[:,1])
            
            # Solve
            if (opti == "ECOS")
                solve_mpc_JuMP(optimizers[1], params, Xhrz, Uhrz; warm_start=false)
            elseif (opti == "SCS")
                solve_mpc_JuMP(optimizers[2], params, Xhrz, Uhrz; warm_start=false)        
            else
                solve_admm!(solver)
                Xhrz .= solver.workspace.x
                Uhrz .= solver.workspace.u
            end
            check_solution!(infos[solver_idx], opti, params, Xhrz, Uhrz)    
            Uhist[:,i] .= Uhrz[:,1]
            
            # print("u = ", Uhist[:,i], "\n")
            # display(Uhist[:,i])

            # Simulate
            Xhist[:,i+1] .= Adyn*Xhist[:,i] + Bdyn*Uhist[:,i] + fdyn
            # display(Xhrz)
            # display(Uhrz)
        end
        infos[solver_idx].tracking_error = norm(Xhist[:,NTOTAL] - xg)
    end
end

### Get data for all solvers for all frequencies

In [81]:
infoss = [[SolnStats(0, 0, 0, 0, 0, 0, 0), SolnStats(0, 0, 0, 0, 0, 0, 0), SolnStats(0, 0, 0, 0, 0, 0, 0)] for i = 1:length(freqs)]
if 1==1
    optis = ["ECOS", "SCS", "TinyMPC"]  # solvers
    freqs = [10.0, 50.0, 100.0, 500.0]  # evaluating frequencies
    for freq_indx = 1:length(freqs)
        freq = freqs[freq_indx]
        optimizers = (
            # Use ECOS [1]
            JuMP.optimizer_with_attributes(ECOS.Optimizer, 
                "verbose"=>false, "abstol"=>1e-2, "reltol"=>1e-2, "maxit"=>round(Int, 1e6/freqs[freq_indx]/tpis[1])),
            # Use SCS [2]
            JuMP.optimizer_with_attributes(SCS.Optimizer, 
            "verbose"=>false, "eps_abs"=>1e-2, "eps_rel"=>1e-2, "max_iters"=>round(Int, 1e6/freqs[freq_indx]/tpis[2])),
            "TinyMPC")
        solver.settings.max_iter = round(Int, 1e6/freqs[freq_indx]/tpis[3])
        infos = infoss[freq_indx]
        for solver_idx = 1:length(optis)
            opti = optis[solver_idx]
            if (opti == "TinyMPC")
                compute_cache!(solver, Q, R)
            end
            
            Random.seed!(1)
            Xhist = zeros(NSTATES, NTOTAL)
            Xhist[:,1] .= x0*1.1
            Uhist = zeros(NINPUTS, NTOTAL-1)

            Xhrz = 1*Xref[:,1:NHORIZON]
            Xhrz[:,1] .= Xhist[:,1]
            Uhrz = 1*Uref[:,1:NHORIZON-1]

            for i = 1:NTOTAL-1
                # i%10 == 0 && print("i = ", i, "\n")
                # Get measurements
                solver.workspace.x[:,1] = Xhist[:,i] 
                Xhrz[:,1] .= Xhist[:,i]
                # print("x = ", solver.workspace.x[:,1], "\n")
                # display(solver.workspace.x[:,1])

                # Update references
                solver.workspace.Xref .= Xref[:,i:i+NHORIZON-1]
                params.Xref .= Xref[:,i:i+NHORIZON-1]
                # solver.workspace.Uref .= Uref[:,i:i+NHORIZON-2]
                # print("xref = ", solver.workspace.Xref[:,1], "\n")
                # display(solver.workspace.Xref[:,1])
                
                # Solve
                if (opti == "ECOS")
                    solve_mpc_JuMP(optimizers[1], params, Xhrz, Uhrz; warm_start=false)
                elseif (opti == "SCS")
                    solve_mpc_JuMP(optimizers[2], params, Xhrz, Uhrz; warm_start=false)        
                else
                    solve_admm!(solver)
                    Xhrz .= solver.workspace.x
                    Uhrz .= solver.workspace.u
                end
                check_solution!(infos[solver_idx], opti, params, Xhrz, Uhrz)    
                Uhist[:,i] .= Uhrz[:,1]
                
                # print("u = ", Uhist[:,i], "\n")
                # display(Uhist[:,i])

                # Simulate
                Xhist[:,i+1] .= Adyn*Xhist[:,i] + Bdyn*Uhist[:,i] + fdyn
                # display(Xhrz)
                # display(Uhrz)
            end
            infos[solver_idx].tracking_error = norm(Xhist[:,NTOTAL] - xg)
        end
    end
end

In [131]:
for freq_idx = 1:length(freqs)
    @printf "-----------------------\n"
    @printf "freq: %d\n" freqs[freq_idx]
    @printf "-----------------------\n"
    for solver_idx = 1:length(optis)
        info = infoss[freq_idx][solver_idx]
        # metric = info.max_bnd_violation + info.max_soc_violation
        metric = info.tracking_error
        @printf "%7s: %10.2f\n" optis[solver_idx] metric
    end
end

-----------------------
freq: 10
-----------------------
   ECOS:       1.33
    SCS:       1.35
TinyMPC:       0.87
-----------------------
freq: 50
-----------------------
   ECOS:       1.33
    SCS:       1.35
TinyMPC:       0.87
-----------------------
freq: 100
-----------------------
   ECOS:       1.33
    SCS:       1.36
TinyMPC:       0.87
-----------------------
freq: 500
-----------------------
   ECOS:     428.76
    SCS:       1.36
TinyMPC:       0.88


In [10]:
fig = plt.figure()
plot(Xref[1,1:NTOTAL-1]) # x
plot(Xhist[1,1:NTOTAL-1])
plot(Xref[2,1:NTOTAL-1]) # y
plot(Xhist[2,1:NTOTAL-1])
plot(Xref[3,1:NTOTAL-1]) # z
plot(Xhist[3,1:NTOTAL-1])
plt.title(opti * " Rocket Landing")
# put limit on axis
# plt.ylim(-5, 20)
# plt.xlim(0, 300)
fig

UndefVarError: UndefVarError: Xhist not defined

In [11]:
fig = plt.figure()
plot(Xref[1,1:NTOTAL-1]) # x
plot(Xhist[1,1:NTOTAL-1])
plot(Xref[2,1:NTOTAL-1]) # y
plot(Xhist[2,1:NTOTAL-1])
plot(Xref[3,1:NTOTAL-1]) # z
plot(Xhist[3,1:NTOTAL-1])
plt.title(opti * " Rocket Landing")
# put limit on axis
# plt.ylim(-5, 20)
# plt.xlim(0, 300)
fig

UndefVarError: UndefVarError: Xhist not defined

In [12]:
fig = plt.figure()
plot(Uhist[1,1:NTOTAL-1])
plot(Uhist[2,1:NTOTAL-1])
plot(Uhist[3,1:NTOTAL-1])
plt.title(opti * " Rocket Landing")
fig

UndefVarError: UndefVarError: Uhist not defined

In [13]:
fig = plt.figure()
plot(Uhist[1,1:NTOTAL-1])
plot(Uhist[2,1:NTOTAL-1])
plot(Uhist[3,1:NTOTAL-1])
plt.title(opti * " Rocket Landing")
fig

UndefVarError: UndefVarError: Uhist not defined

In [14]:
infoss

UndefVarError: UndefVarError: infoss not defined